version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: '/example'
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
