name: CI
on: [push, pull_request]
jobs:
  test:
    name: Lint and Test - Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['10', '12', '14', '15']
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile
      - run: yarn add react
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
